### ISSUE TITLE
Implement fix for indexing CF docs

### ISSUE THREAD

**Issue by ArsHaider** [cloud-gov/product#2138] opened 2022-07-22 22:13 UTC
After determining barriers to indexing CF docs with Cloud Gov knowledge base to implement the indexing of the CF docs.

**Comment by mogul** [comment] 2022-07-29 20:46
Is this a dupe of https://github.com/cloud-gov/product/issues/1780 ?

**Comment by mogul** [comment] 2022-07-29 20:46
(which is already on the Success board)

**Closed** 2022-10-07 19:27 UTC
Labels: squad-success
