### ISSUE TITLE
[devops] Amazon ElastiCache for Redis 3 End Of Life (EOL)

### ISSUE THREAD

**Issue by ArsHaider** [cloud-gov/product#2199] opened 2022-08-25 17:09 UTC
ElastiCache for Redis version 3, originally released in October 2017, will reach its End Of Life (EOL) on July 31, 2023. It is recommended that upgrades be made to cache cluster(s) to the latest available ElastiCache for Redis version before July 31, 2023. At this time, the latest version is 6.2, and it contains features including: JSON support, Redis Streams, performance improvements (including Enhanced IO), and data tiering as well as a various security and reliability updates.

(https://cloud-gov.zendesk.com/agent/tickets/4336)

**Comment by markdboyd** [comment] 2022-10-28 16:32
Closing as duplicate of #2179

**Closed by markdboyd** 2022-10-28 16:32 UTC
Labels: squad-platform, maintenance
