### ISSUE TITLE
Container verification for Concourse

### ISSUE THREAD

**Issue by LindsayYoung** [cloud-gov/product#1658] opened 2022-01-03 18:46 UTC
Validate container we pull is the same one we push

See previous planning:
https://github.com/cloud-gov/product/issues/1543

@davemcorwin has details on how we do this in Concourse

**Comment by bengerman13** [comment] 2022-02-14 18:54
step 1: ADR

We could probably do this for concourse by scanning images, then putting the validated container checksums into credhub, and pulling by checksum rather than tag

**Comment by bengerman13** [comment] 2022-02-28 23:12
ADR open - waiting for review/comments

**Comment by pburkholder** [comment] 2022-11-03 19:56
Closing as duplicate of #1723 (which is more fully fleshed out)

**Closed by pburkholder** 2022-11-03 19:56 UTC
Labels: compliance
